// Code generated by Slice Machine. DO NOT EDIT.

import { defineAsyncComponent } from "vue";
import { defineSliceZoneComponents } from "@prismicio/vue";

export const components = defineSliceZoneComponents({
  header_with_text: defineAsyncComponent(
    () => import("./HeaderWithText/index.vue"),
  ),
  hero: defineAsyncComponent(() => import("./Hero/index.vue")),
  logo_banner: defineAsyncComponent(() => import("./LogoBanner/index.vue")),
  social_medias_block: defineAsyncComponent(
    () => import("./SocialMediasBlock/index.vue"),
  ),
});
